# Generated by Django 3.0.7 on 2020-08-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='link',
            field=models.CharField(default='#', max_length=200, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='misturados',
            name='link',
            field=models.CharField(default='#', max_length=200, verbose_name='Link'),
        ),
    ]
