# Generated by Django 3.0.7 on 2020-08-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_auto_20200804_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentos',
            name='assistir',
            field=models.CharField(default='#', max_length=500, verbose_name='Link para baixar'),
        ),
        migrations.AddField(
            model_name='misturados',
            name='assistir',
            field=models.CharField(default='#', max_length=500, verbose_name='Link para baixar'),
        ),
        migrations.AlterField(
            model_name='lancamentos',
            name='link',
            field=models.CharField(default='#', max_length=500, verbose_name='Link para assistir'),
        ),
        migrations.AlterField(
            model_name='misturados',
            name='link',
            field=models.CharField(default='#', max_length=500, verbose_name='Link para assistir'),
        ),
    ]
